#!/usr/bin/env python
import subprocess
import sys
import csv
import os
from getpass import getpass

if len(sys.argv) != 2:
    print(f"usage: {sys.argv[0]} DATABASE_FILE")
    sys.exit(1)

db = sys.argv[1]
password = getpass()

proc = subprocess.run(["keepassxc-cli", "export", "-f", "csv", db], 
                     input=password,
                     text=True,
                     capture_output=True)
out = proc.stdout
print(proc.stderr)
if proc.returncode:
    sys.exit(1)

tmpfpath = "/tmp/xxx"
with open(tmpfpath, "w", newline='') as tmpf:
    tmpf.write(out)
with open(tmpfpath, "r", newline='') as tmpf:
    csv_reader = csv.DictReader(tmpf)
    for e in csv_reader:
        print(f"[{e["Title"]}]")
        if e["Username"]: print(f"user={e["Username"]}")
        if e["Password"]: print(f"pass={e["Password"]}")
        if e["URL"]:      print(f"url={e["URL"]}")
        if e["TOTP"]:     print(f"totp={e["TOTP"]}")
        if e["Notes"]:
            for line in e["Notes"].split(): print("# ")
        print()

os.remove(tmpfpath)
