#!/usr/bin/env python3
import subprocess
import sys
import csv
import os
import io
from getpass import getpass

if len(sys.argv) != 2:
    print(f"usage: {sys.argv[0]} DATABASE_FILE")
    sys.exit(1)

try: 
    proc = subprocess.Popen(
        ["keepassxc-cli", "export", "-f", "csv", sys.argv[1]],
        stdout=subprocess.PIPE,
        text=True,
    )

    stdout, _ = proc.communicate()
    if proc.returncode:
        sys.exit(proc.returncode)

    csv_reader = csv.DictReader(io.StringIO(stdout))
    for e in csv_reader:
        print(f"[{e["Title"]}]")
        if e["Group"]:         print(f"group={e["Group"]}")
        if e["Username"]:      print(f"user={e["Username"]}")
        if e["Password"]:      print(f"pass={e["Password"]}")
        if e["URL"]:           print(f"url={e["URL"]}")
        if e["TOTP"]:          print(f"totp={e["TOTP"]}")
        if e["Icon"]:          print(f"icon={e["Icon"]}")
        if e["Last Modified"]: print(f"modified={e["Last Modified"]}")
        if e["Created"]:       print(f"created={e["Created"]}")
        if e["Notes"]:
            for line in e["Notes"].splitlines(): print(f"# {line}")
        print()
except KeyboardInterrupt:
    print()
    print("abandon")
